Web.CarRental/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Web.CarRental.ViewModels;
using Web.CarRental.Services;
using System.Linq;
using System.Web.Mvc;

namespace Web.CarRental.Controllers
{
    public class BrandController : BaseController
    {
        private readonly IBrandService<BrandViewModel> _brandService;

        public BrandController(IBrandService<BrandViewModel> brandService)
        {
            _brandService = brandService;
        }

        public IActionResult List()
        {
            var brands = _brandService.List();
            return View(brands);
        }

        public IActionResult Details(int id)
        {
            var brand = _brandService.Get(id);
            return View(brand);
        }

        public IActionResult Update(int id)
        {
            var brand = _brandService.Get(id);
            return View(brand);
        }

        public IActionResult Edit(BrandViewModel brand)
        {
            _brandService.Update(brand);
            return RedirectToAction(Constants.Route.List, Constants.Route.Brand);
        }

        public IActionResult Create()
        {
            if (_brandService.CanCreate())
            {
                return View(new BrandViewModel { });
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }

        public IActionResult Insert(BrandViewModel brand)
        {
            _brandService.Create(brand);
            return RedirectToAction(Constants.Route.List, Constants.Route.Brand);
        }

        public IActionResult Delete(int id)
        {
            if (_brandService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Brand);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }
    }
}

Web.CarRental/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using Web.CarRental.Services;
using Web.CarRental.ViewModels;

namespace Web.CarRental.Controllers
{
    public class CarController : BaseController
    {
        private readonly ICarService<CarViewModel> _carService;
        private readonly IBrandService<BrandViewModel> _brandService;
        private readonly ILocationService<LocationViewModel> _locationService;

        public CarController(ICarService<CarViewModel> carService, IBrandService<BrandViewModel> brandService, ILocationService<LocationViewModel> locationService)
        {
            _carService = carService;
            _brandService = brandService;
            _locationService = locationService;
        }

        public IActionResult List()
        {
            var cars = _carService.List();
            return View(cars);
        }

        public IActionResult Details(int id)
        {
            var car = _carService.Get(id);
            return View(car);
        }

        public IActionResult Update(int id)
        {
            var car = _carService.Get(id);
            car.Brands = _brandService.List();
            car.CurrentLocations = _locationService.List();
            return View(car);
        }

        public IActionResult Edit(CarViewModel car)
        {
            _carService.Update(car);
            return RedirectToAction(Constants.Route.List, Constants.Route.Car);
        }

        public IActionResult Create()
        {
            if (_carService.CanCreate())
            {
                var vm = new CarViewModel
                {
                    Brands = _brandService.List(),
                    CurrentLocations = _locationService.List()
                };
                return View(vm);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }

        public IActionResult Insert(CarViewModel car, BrandViewModel @class)
        {
            _carService.Create(car);
            return RedirectToAction(Constants.Route.List, Constants.Route.Car);
        }

        public IActionResult Delete(int id)
        {
            if (_carService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Car);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }
    }
}

Web.CarRental/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Web.CarRental.ViewModels;
using Web.CarRental.Services;
namespace Web.CarRental.Controllers
{
    public class CommentController : BaseController
    {
        private readonly ICommentService<CommentViewModel> _commentService;
        private readonly IRentService<RentViewModel> _rentService;
        private readonly IUserService<UserViewModel> _userService;
        public CommentController(ICommentService<CommentViewModel> commentService, IRentService<RentViewModel> rentService, IUserService<UserViewModel> userService)
        {
            _commentService = commentService;
            _rentService = rentService;
            _userService = userService;
        }

        public IActionResult List()
        {
            var comments = _commentService.List();
            return View(comments);
        }

        public IActionResult Details(int id)
        {
            var comment = _commentService.Get(id);
            return View(comment);
        }

        public IActionResult Update(int id)
        {
            var comment = _commentService.Get(id);
            comment.Users = _userService.List();
            comment.Rents = _rentService.List();
            return View(comment);
        }

        public IActionResult Edit(CommentViewModel comment)
        {
            _commentService.Update(comment);
            return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
        }

        public IActionResult Create()
        {
            if (_commentService.CanCreate())
            {
                var vm = new CommentViewModel();
                vm.Users = _userService.List();
                vm.Rents = _rentService.List();
                return View(vm);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }

        public IActionResult Insert(CommentViewModel brand)
        {
            _commentService.Create(brand);
            return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
        }

        public IActionResult Delete(int id)
        {
            if (_commentService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }
    }
}

Web.CarRental/Controllers/RentController.cs
using DAL.CarRental.CustomModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Web.CarRental.Services;
using Web.CarRental.ViewModels;

namespace Web.CarRental.Controllers
{
    public class RentController : BaseController
    {
        private readonly IRentService<RentViewModel> _rentService;
        private readonly ICarService<CarViewModel> _carService;
        private readonly IBrandService<BrandViewModel> _brandService;
        private readonly ILocationService<LocationViewModel> _pickupLocationService;
        private readonly ILocationService<LocationViewModel> _returnLocationService;

        public RentController(IRentService<RentViewModel> rentService,
            ICarService<CarViewModel> carService, IBrandService<BrandViewModel> brandService,
            ILocationService<LocationViewModel> pickupLocationService,
            ILocationService<LocationViewModel> returnLocationService)
        {
            _carService = carService;
            _rentService = rentService;
            _brandService = brandService;
            _pickupLocationService = pickupLocationService;
            _returnLocationService = returnLocationService;
        }


        public IActionResult List(FilterRentViewModel viewModel)
        {
            var model = new FilterRentViewModel();
            var rents = new List<RentViewModel>();
            if (viewModel.FilterRent != null)
            {
                if (viewModel.FilterRent.Country != null && viewModel.FilterRent.City != null && viewModel.FilterRent.Model != null && viewModel.FilterRent.Country != null)
                {
                    rents = _rentService.Search(viewModel);
                }
            }
            else
            {
                rents = _rentService.List();
               
            }
            model.RentViewModel = rents;
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var rent = _rentService.Get(id);
            return View(rent);
        }

        public IActionResult Update(int id)
        {
            var rent = _rentService.Get(id);
            rent.Cars = _carService.List();
            rent.PickupLocations = _pickupLocationService.List();
            rent.ReturnLocations = _returnLocationService.List();
            return View(rent);
        }

        public IActionResult Edit(RentViewModel rent)
        {
            _rentService.Update(rent);
            return RedirectToAction(Constants.Route.List, Constants.Route.Rent);
        }

        public IActionResult Book(RentViewModel rent)
        {
            rent.IsAvailable = false;
            _rentService.Update(rent);
            return RedirectToAction(Constants.Route.List, Constants.Route.Rent);
        }


        public IActionResult Create()
        {
            if (_rentService.CanCreate())
            {
                var vm = new RentViewModel();
                vm.Cars = _carService.List();
                vm.PickupLocations = _pickupLocationService.List();
                vm.ReturnLocations = _returnLocationService.List();
                return View(vm);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }

        public IActionResult Insert(RentViewModel rent)
        {
            _rentService.Create(rent);
            return RedirectToAction(Constants.Route.List, Constants.Route.Rent);
        }

        public IActionResult Delete(int id)
        {
            if (_rentService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Rent);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }
    }
}

Web.CarRental/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car rental</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://i.ibb.co/XjDr9Nr/gier.png" width="30" height="30"> Car rental
                </a>

                <!-- Centered link -->
                <div class="topnav-centered">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rent" asp-action="List">Rent</a>
                        </li>
                        @if (@Context.Session.GetString("Role") == "Admin" || @Context.Session.GetString("Role") == "Back Office")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="List">Car</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="List">Brand</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="List">Location</a>
                            </li>
                        }
                        @if (@Context.Session.GetString("Role") == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Comment" asp-action="List">Comment</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="topnav-right">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <div class="btn-group dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Account
                                </a>
                                <div class="dropdown-menu">
                                    @if (@Context.Session.GetString("IsStateLogged") != "true")
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="SignIn">Sign In</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="SignUp">Sign Up</a>
                                    }
                                    @if (@Context.Session.GetString("IsStateLogged") == "true")
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="SignOut">Sign Out</a>
                                    }
                                </div>
                            </div>


                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-2">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="row text-center d-flex justify-content-center pt-10 mb-6">
            <div class="col-md-1 mb-3">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About us</a>
            </div>
            <div class="col-md-1 mb-3">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy policy</a>
            </div>
            <div class="col-md-1 mb-3">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contacts</a>
            </div>
        </div>
        <hr class="rgba-white-light" style="margin: 0 15%;">

        <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
        <div class="footer-copyright text-center py-3">
            © 2019 Copyright:
            <i> Peter Yordanov</i>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>