Web.CarRental/ViewModels/LocationViewModel.cs
using DAL.CarRental.Models;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.CarRental.ViewModels
{
    public class LocationViewModel
    {
        public int LocationId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }
        public string Country { get; set; }
    }
}

Web.CarRental/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using Web.CarRental.Services;
using Web.CarRental.ViewModels;

namespace Web.CarRental.Controllers
{
    public class LocationController : BaseController
    {
        private readonly ILocationService<LocationViewModel> _locationService;

        public LocationController(ILocationService<LocationViewModel> locationService)
        {
            _locationService = locationService;
        }

        public IActionResult List()
        {
            var locations = _locationService.List();
            return View(locations);
        }

        public IActionResult Details(int id)
        {
            var location = _locationService.Get(id);
            return View(location);
        }

        public IActionResult Update(int id)
        {
            var location = _locationService.Get(id);
            return View(location);
        }

        public IActionResult Edit(LocationViewModel location)
        {
            _locationService.Update(location);
            return RedirectToAction(Constants.Route.List, Constants.Route.Location);
        }

        public IActionResult Create()
        {
            if (_locationService.CanCreate())
            {
                return View(new LocationViewModel { });
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }

        public IActionResult Insert(LocationViewModel location)
        {
            _locationService.Create(location);
            return RedirectToAction(Constants.Route.List, Constants.Route.Location);
        }

        public IActionResult Delete(int id)
        {
            if (_locationService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Location);
            }
            return RedirectToAction(Constants.Route.SignIn, Constants.Route.User);
        }
    }
}

Web.CarRental/Views/Location/Create.cshtml
@model Web.CarRental.ViewModels.LocationViewModel
@{
    ViewBag.Title = "Location new";
}

<form asp-action="Insert" asp-controller="Location">
    <div class="card border-primary mb-5">
        <div class="card-header border-primary">
            <div class="row">
                <label class="col">Location new</label>
            </div>
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="PostalCode" class="control-label"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Street" class="control-label"></label>
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="form-row mb-6">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

Web.CarRental/Views/Location/Details.cshtml
@model Web.CarRental.ViewModels.LocationViewModel
@{
    ViewBag.Title = "Location details";
}

<div class="card border-info mb-5">
    <div class="card-header border-info">
        <div class="row">
            <label class="col">Location details</label>
        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>@Html.DisplayNameFor(model => model.Country)</label>
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
            <div class="form-group col-md-6">
                <label>@Html.DisplayNameFor(model => model.City)</label>
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>@Html.DisplayNameFor(model => model.PostalCode)</label>
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
            <div class="form-group col-md-6">
                <label>@Html.DisplayNameFor(model => model.Street)</label>
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>
        <hr />
        <a asp-action="Update"  class="btn btn-info"  asp-route-id="@Model.LocationId">Edit</a>
    </div>
</div>

Web.CarRental/Views/Location/List.cshtml
@model IEnumerable<Web.CarRental.ViewModels.LocationViewModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="row p-2">
        <div class="col-sm-12" align="right">
            <a asp-action="Create" class="btn btn-outline-primary">Create new location</a>
        </div>
    </div>
    <div class="row p-2">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Country)</h5>
                        <div>
                            <p class="card-text">@Html.DisplayFor(modelItem => item.City)</p>
                        </div>
                        <br />
                        <hr />
                        <a asp-action="Details" class="btn btn-outline-info" asp-route-id="@item.LocationId">Details</a>
                        <a asp-action="Update" class="btn btn-outline-warning" asp-route-id="@item.LocationId">Edit</a>
                        <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.LocationId">Delete</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Web.CarRental/Views/Location/Update.cshtml
@model Web.CarRental.ViewModels.LocationViewModel
@{
    ViewBag.Title = "Location edit";
}

<form asp-action="Edit" asp-controller="Location">
    <div class="card border-warning mb-5">
        <div class="card-header border-warning">
            <div class="row">
                <label class="col">Location edit</label>
            </div>
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="PostalCode" class="control-label"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Street" class="control-label"></label>
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row mb-6">
                <input asp-for="LocationId" class="form-control" hidden="hidden" />
                <input type="submit" value="Edit" class="btn btn-warning" />
            </div>
        </div>
    </div>
</form>